
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables from .env file
config();

import path from "path";

const getDatabaseUrl = () => {
  if (process.env.APP_ENV === 'staging') {
    return `${process.env.TURSO_DATABASE_URL}?authToken=${process.env.TURSO_AUTH_TOKEN}`;
  }
  
  const url = process.env.DATABASE_URL || "file:./dev.db";
  if (url.startsWith('file:')) {
    const dbPath = url.replace('file:', '');
    const absolutePath = path.isAbsolute(dbPath)
      ? dbPath
      : path.join(process.cwd(), 'prisma', dbPath.replace(/^\.\//, ''));
    return `file:${absolutePath}`;
  }
  return url;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: getDatabaseUrl(),
  },
});
